import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "./ui/navbar/ResponsiveNav";
import Providers from "./providers";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Solon-Booking-System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} antialiased`}
      >
        <Providers>
          <ResponsiveNav />
          {children}
        </Providers>
      </body>
    </html>
  );
}
